name: pengembanganlanjut
description: "Proyek Flutter baru."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logolanjut.jpeg
    - assets/fotoprofile.jpeg
    - assets/gambar1.jpg
    - assets/gambar2.jpg
    - assets/gambar3.jpg
    - assets/gambar4.jpg
    - assets/gambar5.jpg
